### ISSUE TITLE
Pretrained teacher models

### ISSUE THREAD

**Issue by AiXia520** [penghui-yang/L2D#3]
Could the pretrained teacher models be downloaded?

**Comment by penghui-yang** [comment]
Sorry, I cannot provide pre-trained teacher model weights now. I deleted them because they occupied too much storage space. 
You can retrain the teacher models by simply setting `teacher_pretrained = False` in the config file. I will add more instructions about the config file in the README.md in the next version.

**Comment by penghui-yang** [comment]
I hope commit `4d87eaa` can solve your problem :)
